### ISSUE TITLE
Feedback functions

### ISSUE THREAD

**Issue by alexanderhingston** [bitfocus/companion-module-resi-decoders#6]
Not an issue, but I use your module in church for our resi decoder. Is there any chance of getting feedback functions for countdowns to cues, cue names, things like that. What I wanted to do was have it so that when companion receives the feedback that the cue “Keys Up” has been received, it takes the countdown and sends it in a message (have the message part set up already). Please let me know if it is possible. If it’s easier feel free to email me - alexanderhingston@gmail.com

**Comment by jakenjones** [comment]
We haven't used our Resi decoder for some time now and I no longer maintain
the repository myself. From what  I have read, Resi does not support
feedback. If you can find  some documentation on where they do provide
feedback, I would be happy to work on an implementation of it.

Jake
